### ISSUE TITLE
could not copy files at all

### ISSUE THREAD

**Issue by vizmi** [calvinmetcalf/copyfiles#1]
I have tried to do a simple file copy with this command:

`.\node_modules\.bin\copyfiles ./src/index.html ./client`

but it fails with the following error message:

`\node_modules\copyfiles\node_modules\glob\glob.js:130
    throw new Error("must provide pattern")`

I have tried to use both ' and " around the paths, / and \ as path separator but I could not get it running.

OS: Windows 7 Pro
Node version: 0.12.0
NPM version: 2.5.1

**Comment by calvinmetcalf** [comment]
fixed by v0.1.1

**Comment by vizmi** [comment]
Thanks for the quick fix, it works now.
