### ISSUE TITLE
Works from CLI, but not from npm scripts

### ISSUE THREAD

**Issue by tyrsius** [calvinmetcalf/copyfiles#10]
I've tried this with a couple commands, and I'm not sure what the issue is, but using `npm run` to run a script with `copyfiles` in it doesn't work. The same command as `./node_modules/.bin/copyfiles` works fine

**Comment by NogsMPLS** [comment]
Same issue here, running on Windows

**Comment by calvinmetcalf** [comment]
what exactly is the error you're getting?

**Comment by NogsMPLS** [comment]
no error at all, it just...doesnt move the files

**Comment by NogsMPLS** [comment]
or maybe i should clarify.

if i npm install ***-g*** it works.

if however, im trying to not install it globally, but rather straight through npm as a package in a project, it doesnt move files.

**Comment by calvinmetcalf** [comment]
what npm and what node versions do you have installed?

**Comment by NogsMPLS** [comment]
not at computer right now to give exact, but node 4.2.x and npm 2.14.x

**Comment by calvinmetcalf** [comment]
when you get back to your computer can you try the with-logging branch and
add DEBUG=\"copyfiles:*\" to the begining of your npm script where you are
having the problem? (use calvinmetcalf/copyfiles#with-logging as the
version)

**Comment by NogsMPLS** [comment]
Okay, yeah that branch helped a lot. I think I figured out my issue

I had ```copyup './components/**/*.css' lib```. note the quotes. removing the quotes fixed this.

However, my project is a open source lib, so I'll eventually need it to be able to work on Mac and Win.

My problem is solved for now, but I may come back later and spend some time and submit a pull request to try and make this functionality environment agnostic, if that's alright with you.

**Comment by calvinmetcalf** [comment]
hm weird quotes work on a mac where they are actually useful in preventing the shell from handling the glob in a broken manner

**Comment by NogsMPLS** [comment]
yeah, looks like quotes work on mac, but not windows. =/

**Comment by goerp** [comment]
Using escaped double quotes in stead of single quotes works for me (windows 7, npm@3.7.1 node@v5.6.0):
npm command: 
>   npm run assets 

where 'assets' is:
copyfiles -u 1 \"./src/**/*+(.eot|.ttf|.woff)\" dist

Now to test if it still works on Mac

**Comment by RyanZim** [comment]
@goerp is right, windows can't handle single quotes. Use double quotes for cross-platform usage. @calvinmetcalf This can be closed IMO.

**Comment by FireController1847** [comment]
WOOOW. I spent three hours having this issue with 5 different modules, and it's all because I wasn't using quotes. I cannot believe how hard it was to find this fix. Thanks guys, seriously.
