### ISSUE TITLE
Bug: Copyfiles 2.4.1 doesn't work

### ISSUE THREAD

**Issue by DanilAndreev** [calvinmetcalf/copyfiles#100]
# Bug Report
## Overview
When I am trying to copy my files I get next error:
```
  outDir = outDir.startsWith('~') ? untildify(outDir) : outDir;
                  ^

TypeError: Cannot read property 'startsWith' of undefined

```

My copyfiles script:
```
copyfiles --up 2 "src/**/*.hbs" dist --verbose
```

## Expected 
In version ```2.3.0``` everything works as expected.

## Versions
__Copyfiles__ -  ```2.4.1```
__NodeJS__ - ```12.18.2```
__Yarn__ - ```1.22.4```

**Comment by DanilAndreev** [comment]
I am the lucky owner of issue number 100. :smiley:

**Comment by calvinmetcalf** [comment]
could you edit node_modules/.bin/copyfiles and put a `console.log(argv);` right before line 40?

**Comment by DanilAndreev** [comment]
Now everything works as expected on the version ```2.4.1```. Don't know what happened a week ago 😃. Thanks. Maybe yarn incorrectly installed the package twice.
