### ISSUE TITLE
Redo the out dir arg

### ISSUE THREAD

**Issue by corysimmons** [calvinmetcalf/copyfiles#11]
`copyfiles assets/src/img/**/* assets/dist/img` should copy all the files in `assets/src/img` to `assets/dist/img`.

I've tried a dozen ways to copy files to the correct location and can't figure it out.

Gonna make my own copyfiles package. No need for a reply.

**Comment by calvinmetcalf** [comment]
feel free to open a pull, but you should try `copyfiles -u 3 assets/src/img/* assets/dist` first

**Comment by corysimmons** [comment]
I made my own little CLI that does this, but then I realized that both our libs are just replicating `cp` functionality in a worse way. :)

**Comment by calvinmetcalf** [comment]
> I made my own little CLI that does this, but then I realized that both our libs are just replicating cp functionality in a worse way. :)

this is intentional for the time we must work with our less enlightened brethren on windows.

**Comment by corysimmons** [comment]
Oh, haha, I see. Poor bastards.:(
