### ISSUE TITLE
Recursive glob doesn't work?

### ISSUE THREAD

**Issue by dy** [calvinmetcalf/copyfiles#122]
Hi! I'm running 
```
copyfiles -u 1 src/**/*.css dist/
```
and I can see that `src/a/b/c.css` doesn't get copied.
I have to add `copyfiles -u 1 src/**/**/*.css src/**/*.css dist/` to make it work.

Is that by design or I'm doing something wong?

**Comment by dy** [comment]
Ok, found out it needs to be `copyfiles -u 1 "src/**/*.css" dist/`

**Comment by 2ico** [comment]
Why though?
