### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by popenkomaksim** [calvinmetcalf/copyfiles#14]
This package is pretty cool, thanks for sharing, but unfortunately 

Try to copy 6000+ json files and got error:
sh: /usr/local/bin/copyfiles: Argument list too long

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "copy-json"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! judges@0.0.1 copy-json: `copyfiles source/*.json declarations/*.json ./dist/ && echo 'JSON files copied.'`
npm ERR! Exit status 126

Could you please confirm that there are some limitations for copping files?

**Comment by calvinmetcalf** [comment]
assuming your using a glob from the command line, surround it in quotations so it doesn't get interpolated until it gets inside the module

**Comment by popenkomaksim** [comment]
`copyfiles some.json './some_folder/*.json' ./dist/ && echo 'JSON files copied.'`
– works like a charm!
Thanks!
