### ISSUE TITLE
-u 1 doesn't work with globstars

### ISSUE THREAD

**Issue by mkimmet** [calvinmetcalf/copyfiles#17]
When trying to copy the files and folders from one folder to another using globstars and -u 1:
    
    copyfiles -u 1 ./dist/** ../Angular2Test/Content/myapp

It gives this error:

K:\dev\Angular2Test\Angular2Source\node_modules\copyfiles\index.js:30
    throw new Error('cant go up that far');
    ^

Error: cant go up that far
    at dealWith (K:\dev\Angular2Test\Angular2Source\node_modules\copyfiles\index
.js:30:11)
    at K:\dev\Angular2Test\Angular2Source\node_modules\copyfiles\index.js:64:39
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by calvinmetcalf** [comment]
a couple questions

- is there a file named dist?
- what folder are you in when running this script?

**Comment by mkimmet** [comment]
Thanks for the response!

- dist is a folder that contains a few files and a subfolder called assets
- When I run this, I'm running it from the folder that contains the dist folder.

Just a few side notes that might be helpful.  

1. The following command works, using one star instead of two.  However, I want it to also copy the "assets" subfolder, which this command doesn't do:

    copyfiles -u 1 ./dist/* ../Angular2Test/Content/myapp

2. The following command works, and it copies the subfolder "assets" and it's contents. However, since it's not using -u 1 it copies it into a folder called dist in my destination, which I don't want.  

    copyfiles ./dist/** ../Angular2Test/Content/myapp

**Comment by calvinmetcalf** [comment]
try putting ./dist** in quotes

**Comment by mkimmet** [comment]
When I try with single quotes around it, it acts like it works, but then there are no files in the myapp folder.  If I try with double quotes it gives the "cant go up that far" error.

**Comment by calvinmetcalf** [comment]
ok strange, I will try to test when I have some time latter

**Comment by mkimmet** [comment]
I tried the following with no luck:

    copyfiles -u 1 \"./dist/*/\" ../Angular2Test/Content/myapp

    copyfiles -u 1 \"./dist/**/\" ../Angular2Test/Content/myapp

    copyfiles -u 1 \"./dist/**\" ../Angular2Test/Content/myapp

I've gone in a different direction at this point, so this is not a critical issue to address, but it would be nice to know.

**Comment by jeremymoritz** [comment]
@mkimmet You didn't use the same syntax.  Use "**/*".  Try this:

`copyfiles -u 1 \"./dist/**/*\" ../Angular2Test/Content/myapp**/*`

**Comment by calvinmetcalf** [comment]
the important part is the **/* on both sides and the fact that we have
double quotes, the escaping is only important inside of json

**Comment by mkimmet** [comment]
@jeremymoritz @calvinmetcalf Perfect!  I must've missed that extra star.  Works now!
