### ISSUE TITLE
Requires escaped double-quotes for cross-platform globstars **/*

### ISSUE THREAD

**Issue by jeremymoritz** [calvinmetcalf/copyfiles#18]
One thing i noticed in the documentation is that your examples show single-quoted strings in order to allow for cross-platform compatibility.  I have tried this and it does not work properly in Windows.  However using ESCAPED DOUBLE-QUOTES works great!

So instead of...

copyfiles -f './foo/*_/_.txt' out

try...

copyfiles -f \"./foo/*_/_.txt\" out

Can you please update the documentation to show this?

Thanks!

Jeremy Moritz

**Comment by calvinmetcalf** [comment]
What context are you running this in? A package.json per chance?

**Comment by jeremymoritz** [comment]
yes that's correct.  sorry i should've mentioned that

Jeremy Moritz
913-980-5376

**Comment by calvinmetcalf** [comment]
Ok so the fact that you are in a package.json is why it needs to be
escaped, as for why it needs to be double quotes, what happens when you use
single quotes?

**Comment by jeremymoritz** [comment]
Nothing is copied when the line runs with single quotes on Windows machine
(though it works properly on a Mac).  Just double-checked it.  I'm using
all three environments (Windows, Linux, and Mac), and the escaped
double-quotes is the only one that works in all three.

Jeremy Moritz
913-980-5376

**Comment by cellvia** [comment]
same here

**Comment by calvinmetcalf** [comment]
readme is updated
