### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by mmc41** [calvinmetcalf/copyfiles#19]
Great tool (the -u option is especially nice). Would it be possible to add an exclude option in order to f.x. copy all files according to a glob except a specific file type ?

**Comment by calvinmetcalf** [comment]
so an exclude glob basically?

**Comment by mmc41** [comment]
Yes that would be great (if exposed to the CLI as an command line option):

Example (copy all files from src/datasets except typescript files to dist dir):
copyfiles -u 1 -exclude **/*.ts src/datasets/**/*.* dist

**Comment by calvinmetcalf** [comment]
done with version 1.1.0, -e or --exclude

**Comment by mmc41** [comment]
Super great! Thanks :-)
