### ISSUE TITLE
How can i override a file silently?

### ISSUE THREAD

**Issue by liangklfang** [calvinmetcalf/copyfiles#23]
Error: EEXIST: file already exists, mkdir 'C:\Users\Administrator\Desktop\generator-sy-template\generators\app\config\wcf.config.json'
    at Error (native)

I want files be override silently without such kind of errors

**Comment by calvinmetcalf** [comment]
so that is actually the default behavior

**Comment by MDUK0001** [comment]
I got caught out by this, for anyone else's benefit what I was doing wrong was trying to rename the file at the same time. This is my command:
```
copyfiles -u 1 ./env/config.local.json env/config.json
```
And I get this error:
```
[Error: EEXIST: file already exists, mkdir '[snipped]/env/config.json']
```
The problem is that this tool doesn't support renaming files, so the second parameter has to be just a directory name.
