### ISSUE TITLE
unable to run copyfiles

### ISSUE THREAD

**Issue by beingbing** [calvinmetcalf/copyfiles#27]
![screenshot from 2017-08-07 12 41 48](https://user-images.githubusercontent.com/26813160/29017103-09f4e008-7b73-11e7-90c9-a3a6ba2d8572.png)
sir,
i am trying to make a copy of files using npm copyfiles package but it is giving me error, cn you explain me what i am doing wrong

**Comment by calvinmetcalf** [comment]
if you've run `npm install -g copyfiles` just run `copyfiles` you don't need to put the `npm run` in there.

**Comment by beingbing** [comment]
thanks sir, it worked :+1:
