### ISSUE TITLE
executable permission is removed from copied files

### ISSUE THREAD

**Issue by kyeotic** [calvinmetcalf/copyfiles#29]
Title says it all. When copying files the "executable" permission is removed. Very frustrating

**Comment by calvinmetcalf** [comment]
hm I wonder what the best way to copy permissions is that works on windows too

**Comment by tyrsius** [comment]
The fs module can copy file permissions in a cross-compatible way. Other
modules do this, check out node-fs-extra, it has a copy method that
maintains permissions.
