### ISSUE TITLE
Copy without creating of subdirectories

### ISSUE THREAD

**Issue by devlato** [calvinmetcalf/copyfiles#30]
Let's consider we have the following structure:
```
|-- src
    |-- fonts
        |-- font1.woff
        |-- font2.woff
    |-- index.js
|-- lib
``` 
The command ```copyfiles src/fonts/** lib/fonts/``` creates the following structure:
```
|-- src
    |-- fonts
        |-- font1.woff
        |-- font2.woff
    |-- index.js
|-- lib
    |-- src
        |-- fonts
            |-- font1.woff
            |-- font2.woff
```
Is there any flag not to created the nested directory structure? I need something like this:
```
|-- src
    |-- fonts
        |-- font1.woff
        |-- font2.woff
    |-- index.js
|-- lib
    |-- fonts
        |-- font1.woff
        |-- font2.woff
```

**Comment by calvinmetcalf** [comment]
the `-up` flag takes a number and removes that number of directories from the output so you probably want `-up 1`.

**Comment by rimiti** [comment]
Thanks @calvinmetcalf !

**Comment by drcmda** [comment]
@calvinmetcalf sometimes the number isn't known, for instance in one of our apps we resolve a relative path like `/Users/drcmda/dev/build/assets/**/*` - it could anything on any machine for any user. But i just want to copy the contents of assets into another folder. Is there another solution for this?

**Comment by calvinmetcalf** [comment]
yes the -f option flattens everything
