### ISSUE TITLE
dot folders not being copied even with escaped quotes

### ISSUE THREAD

**Issue by ThadHouse** [calvinmetcalf/copyfiles#36]
I tried doing the fix shown in #18, and that is not working to solve my issue. I am running

`copyfiles -u 4 \\\"../../gradleBase/java/**/*\\\" resources/src/java/gradlebase`

I've also tried `copyfiles -u 4 \"../../gradleBase/java/**/*\" resources/src/java/gradlebase`

and neither one works. My from folder has 2 dot folders with files in them, and neither one is being copied.

**Comment by calvinmetcalf** [comment]
did you close this because you realized the -a option was what would fix it?   

if not then that's the solution

**Comment by ThadHouse** [comment]
Yeah I hadn't seen that option, and the fixes in 18 didn't show -a either.
