### ISSUE TITLE
patterns that include subfolders (i.e. /**/* or /**) fail

### ISSUE THREAD

**Issue by vizmi** [calvinmetcalf/copyfiles#4]
I have a folder structure like this:
- input
  - input1
    - file1.txt
    - file2.txt

When I run this command it fails: `node copyfiles input/**/* output`
Working theory:
- the glob pattern includes the input1 folder (on windows it comes earlier than the files).
- The module tries to open a reader - writer stream on it, which creates an empty file called output/input/input1.
- Any subsequent operations fail because output/input/input1 is not a directory.

**Comment by calvinmetcalf** [comment]
should be fixed in 1.1.2

**Comment by vizmi** [comment]
This works on now, thank you very much!
