### ISSUE TITLE
copyfiles doesn't follow directories that are symlinks

### ISSUE THREAD

**Issue by zbigg** [calvinmetcalf/copyfiles#40]
As in title
This is consistent with `glob` which by default doesn't follow folder symlink. Howewver, `glob` supports `follow` flag to override this. It would be cool is `copyfiles` support that too.

Adding this when preparing `globOpts` helps:
```
if (config.follow) {
    globOpts.follow = true;
}
```

I will prepare PR for this if there is positive feedback.

**Comment by calvinmetcalf** [comment]
sure pr away
