### ISSUE TITLE
[BUG]: Copyfiles Incorrectly Assigns Up

### ISSUE THREAD

**Issue by jd-carroll** [calvinmetcalf/copyfiles#44]
Steps to Reproduce:
```
$ mkdir ~/folder-with-a-up-in-path && cd $_
$ npm init -y
$ npm install copyfiles
$ # open package.json and add the following line to "scripts"
    "copyfiles": "copyfiles package.json dist/lib"
$ npm run copyfiles
Error: cant go up that far
    at dealWith (/home/user/folder-with-a-up-in-path/node_modules/copyfiles/index.js:30:11)
    at /home/user/folder-with-a-up-in-path/node_modules/copyfiles/index.js:80:39
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**The issue is that the script is being run in a folder with a literal `-up` in the path**

The root of the issue the following [block of code](https://github.com/calvinmetcalf/copyfiles/blob/master/copyfiles#L9-L11):
```javascript
if (args.argv.$0.indexOf('up') > -1) {
  args.default('u', '1');
}
```

This looks like it is trying to assign / detect a default value if `-u` is ever specified without a value, the problem is it isn't.  First of all it is incomplete code, it only works with `-up` and not `-u`.  Second the `args.argv.$0` will never contain accurate runtime args, it will [only contain the folder](https://github.com/yargs/yargs/blob/master/yargs.js#L45-L46).  

This code creates a really nasty bug.  I know `yargs` doesn't make it easy to support this functionality, the code above should be removed.

**Comment by jd-carroll** [comment]
I'd also note that the recent release of yargs@12.0 may help solve this issue:
https://github.com/yargs/yargs/blob/master/CHANGELOG.md#features

*Options absent from `argv` (not set via CLI argument) are now absent from the parsed result object rather than being set with `undefined`

**Comment by calvinmetcalf** [comment]
what we're actually doing is seeing if the script was called as `copyfiles` or `copyup` and if it is called as copyup we have a different default value for the `u` parameter the issue is we are seeing is that I'm just looking for the word `up` in the results not, that it was called as copy up so I need to fix that logic

**Comment by jd-carroll** [comment]
That works great, thank you!  I missed that additional logic and get what you are trying to provide.
