### ISSUE TITLE
copy files does not copy dot files even when using the -a flag

### ISSUE THREAD

**Issue by PSPanesar** [calvinmetcalf/copyfiles#52]
Hi,

Im using copyfiles in my npm scripts but the dot files are not being copied at all even when using the -a flag.

`
"scripts": {
    "copy": "rimraf ./dist && copyfiles -a -u 1 templates/**/** dist/templates"
}
`

I wonder if you could help with whats going wrong?

Bw
P

**Comment by calvinmetcalf** [comment]
try `templates/**/*` (only 1 star in the second position) and if that doens't work try wraping it in `\"`
