### ISSUE TITLE
-u option does not work

### ISSUE THREAD

**Issue by vizmi** [calvinmetcalf/copyfiles#6]
Hi Calvin,

apologies for the confusion: I was somewhat convinced the isFile() filtering will fix the -u issue too. It turned out it is not. The 4 test cases with -u are still failing for me.
I have committed the a version to my clone that I believe fixes the issue (the path.normalize call we've been going back and forth) and some logging that helps further diagnostics in the future. I hope you will find it useful.
Let me know if you need a pull request from my end.

**Comment by davidfurlong** [comment]
Still broken :S

**Comment by vizmi** [comment]
My changes never made it to the main code line

**Comment by HoldYourWaffle** [comment]
Is there any update on this?

**Comment by vizmi** [comment]
My changes were lost long before this conversation reopened, sorry.
I am affraid only the original author can help here.

**Comment by vizmi** [comment]
too old to fix
