### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [calvinmetcalf/copyfiles#80]
I just saw the package is updated to `v2.2.0`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @calvinmetcalf! 🙂

**Comment by calvinmetcalf** [comment]
you can check the commits to see which ones came before the V2.2.0 tag

**Comment by MichaelDeBoey** [comment]
@calvinmetcalf I can, but that way I have to dive into the individual commits myself to know what's happening.
It would be way user-friendly if I could just look at the CHANGELOG an read what changed there
