### ISSUE TITLE
Is there a way to copy files that doesn't end with the specified file type?

### ISSUE THREAD

**Issue by cerino-ligutom** [calvinmetcalf/copyfiles#82]
Like for example, move all files to the `out` folder that doesn't with `.ts` from `src/**/*` folder?

**Comment by calvinmetcalf** [comment]
that stuff is all done via https://github.com/isaacs/node-glob so if you can do it there, it works here

**Comment by cerino-ligutom** [comment]
> that stuff is all done via https://github.com/isaacs/node-glob so if you can do it there, it works here

It supports it, thanks!
