### ISSUE TITLE
not working with Windows 10

### ISSUE THREAD

**Issue by wunaidage** [calvinmetcalf/copyfiles#89]
my command is `copyfiles -f ~/checkout/config.js './dist/configurations/'`
I use yarn to run it so the real command is `yarn copyfiles -f ~/checkout/config.js './dist/configurations/'`
it works on macos and linux
it does not work with windows 10. 
I tried all double / single quote on both source and destination part

the powershell output:
``` 
PS D:\jenkins\workspace\some_project\e2e> yarn copyfiles -f -V "~/checkout/config.js" dist/
yarn run v1.21.1
$ D:\jenkins\workspace\some_project\e2e\node_modules\.bin\copyfiles -f -V ~/checkout/config.js dist/
Done in 1.17s.
```
I tried to change the source directory to random garbage name which even not exist but it does not show any error

**Comment by wunaidage** [comment]
I find that tilde sign is not supported by fs. Devs need to expand it manually. 
so it's a miracle for me that macos and linux works.
but I believe in science more so I modified the code a little bit and published to npm to support the tilde sign for home directory
https://www.npmjs.com/package/@wunaidage/copyfiles

should I PR it?

**Comment by calvinmetcalf** [comment]
sure open a pr

**Comment by wunaidage** [comment]
https://github.com/calvinmetcalf/copyfiles/pull/90 thank you PR request
