### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by dotnetCarpenter** [calvinmetcalf/copyfiles#9]
>### copyup
>also creates a copyup command which is identical to copyfiles but `-up` defaults to 1

What does that even mean?

Also it is possible to move directories and not only files? I searched but couldn't find another node cli tool to do it with.
I got something like this:
`copyfiles -f frontend/assets/images/* app/public/images & copyfiles -f frontend/assets/fonts/* app/public/fonts` but it would be a lot easier if I could do:
`copyfiles -f frontend/assets/* app/public/`

**Comment by calvinmetcalf** [comment]
the up option strips out a layer of the outputs folder, so without it, if you did

```bash
copyfiles frontend/assets/images/*.png  out/
```
an image `frontend/assets/images/foo.png` would be now `out/frontend/assets/images/foo.png` the --up option strips off layers of the output directory so 


```bash
copyfiles -u 1 frontend/assets/images/*.png  out/
```

would give you `out/assets/images/foo.png` (no `frontend`), -u 2 would give you  `out/images/foo.png` etc, it's not required if you use the -f option which removes all folders from the output

as for your other question 

```bash
copyfiles -f frontend/assets/images/**/* app/public/
```
probably does what you want

**Comment by dotnetCarpenter** [comment]
Actually `copyfiles -u 2 frontend/assets/**/* app/public/` gives me the 2 folders that I want, e.i. `fonts`and `images`.
This is great! Perhaps just adding to the README:
```
 Usage: copyfiles [options] inFile [more files ...] outDirectory

  Options:

    -h, --help         output usage information
    -V, --version      output the version number
    -u, --up [levels]  slice a path off the bottom of the paths
    -f, --flat         flatten the output
```
and a small example.

I'm trying to follow the logic and want to move some .js files while retaining the folder structure.
```
frontend/
|_javascripts/
  |_scale.js
  |_etc
  |_vendors/
    |_jquery(
    |_etc
```
`copyfiles -up frontend/javascripts/**/* app/public/javascripts/` but nothing happens. Not even an error message. Is it possible to get some debug information?

Thanks for a great module!

**Comment by dotnetCarpenter** [comment]
sorry. My issue was windows paths. I checked in my terminal and needed to use `copyfiles -u 1 frontend\javascripts\**\* app\public\` while in package.json I need to use `copyfiles -u 1 frontend/javascripts/**/* app/public/`. Problem solved :+1:
